name       : signon-ui
version    : 0.17
release    : 2
source     :
    - https://gitlab.com/accounts-sso/signon-ui/-/archive/0.17+15.10.20150810-0ubuntu1/signon-ui-0.17+15.10.20150810-0ubuntu1.tar.gz : c5be19d6f5e6546acf18bd3c840810b1174511d7043c51860959a449c470df10
license    : GPL-3.0-only
component  : programming
summary    : Signond Qt UI
description: |
    Signond Qt UI
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libnotify)
    - pkgconfig(libproxy-1.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebKitWidgets)
    - pkgconfig(signond)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="$installdir"
